import NavBar from '@/components/NavBar';

export const metadata = {
  title: 'commerce.',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={`flex min-h-screen flex-col items-center`}>
      <NavBar />
      {children}
    </div>
  );
}
